<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <InternalsVisibleTo Include="Equibles.UnitTests" />
    <InternalsVisibleTo Include="Equibles.IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Equibles.Core.AutoWiring" />
    <PackageReference Include="HtmlAgilityPack" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="PdfPig" />
    <PackageReference Include="Polly" />
    <PackageReference Include="FlexLabs.EntityFrameworkCore.Upsert" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Equibles.Core\Equibles.Core.csproj" />
    <ProjectReference Include="..\Equibles.Sec.BusinessLogic\Equibles.Sec.BusinessLogic.csproj" />
    <ProjectReference Include="..\Equibles.Sec.FinancialFacts.BusinessLogic\Equibles.Sec.FinancialFacts.BusinessLogic.csproj" />
    <ProjectReference Include="..\Equibles.Integrations.Sec\Equibles.Integrations.Sec.csproj" />
    <ProjectReference Include="..\Equibles.Integrations.XbrlFilings\Equibles.Integrations.XbrlFilings.csproj" />
    <ProjectReference Include="..\Equibles.CommonStocks.BusinessLogic\Equibles.CommonStocks.BusinessLogic.csproj" />
    <ProjectReference Include="..\Equibles.InsiderTrading.Repositories\Equibles.InsiderTrading.Repositories.csproj" />
    <ProjectReference Include="..\Equibles.InsiderTrading.BusinessLogic\Equibles.InsiderTrading.BusinessLogic.csproj" />
    <ProjectReference Include="..\Equibles.CorporateActions.Repositories\Equibles.CorporateActions.Repositories.csproj" />
    <ProjectReference Include="..\Equibles.Yahoo.Repositories\Equibles.Yahoo.Repositories.csproj" />
    <ProjectReference Include="..\Equibles.Media.BusinessLogic\Equibles.Media.BusinessLogic.csproj" />
    <ProjectReference Include="..\Equibles.Errors.BusinessLogic\Equibles.Errors.BusinessLogic.csproj" />
    <ProjectReference Include="..\Equibles.Worker\Equibles.Worker.csproj" />
    <ProjectReference Include="..\Equibles.Messaging\Equibles.Messaging.csproj" />
  </ItemGroup>
</Project>
