<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Equibles.Core/Equibles.Core.csproj" />
    <ProjectReference Include="../Equibles.Integrations.Common/Equibles.Integrations.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Equibles.UnitTests" />
  </ItemGroup>
</Project>
