<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <InternalsVisibleTo Include="Equibles.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Equibles.Core.AutoWiring" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Equibles.EquityMarkets.Repositories\Equibles.EquityMarkets.Repositories.csproj" />
    <ProjectReference Include="..\Equibles.CommonStocks.BusinessLogic\Equibles.CommonStocks.BusinessLogic.csproj" />
    <ProjectReference Include="..\Equibles.CommonStocks.Repositories\Equibles.CommonStocks.Repositories.csproj" />
    <ProjectReference Include="..\Equibles.Integrations.Esma\Equibles.Integrations.Esma.csproj" />
    <ProjectReference Include="..\Equibles.Integrations.Gleif\Equibles.Integrations.Gleif.csproj" />
    <ProjectReference Include="..\Equibles.Worker\Equibles.Worker.csproj" />
  </ItemGroup>
</Project>
