<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <InternalsVisibleTo Include="Equibles.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Equibles.Core.AutoWiring" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Equibles.Core\Equibles.Core.csproj" />
    <ProjectReference Include="..\Equibles.DelayedTrades.BusinessLogic\Equibles.DelayedTrades.BusinessLogic.csproj" />
    <ProjectReference Include="..\Equibles.DelayedTrades.Repositories\Equibles.DelayedTrades.Repositories.csproj" />
    <ProjectReference Include="..\Equibles.EquityMarkets.Repositories\Equibles.EquityMarkets.Repositories.csproj" />
    <ProjectReference Include="..\Equibles.Errors.BusinessLogic\Equibles.Errors.BusinessLogic.csproj" />
    <ProjectReference Include="..\Equibles.Integrations.DelayedTrades\Equibles.Integrations.DelayedTrades.csproj" />
    <ProjectReference Include="..\Equibles.Integrations.Euronext\Equibles.Integrations.Euronext.csproj" />
  </ItemGroup>
</Project>
