<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <InternalsVisibleTo Include="Equibles.UnitTests" />
    <InternalsVisibleTo Include="Equibles.IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Equibles.Core.AutoWiring" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Equibles.Core\Equibles.Core.csproj" />
    <ProjectReference Include="..\Equibles.CommonStocks.BusinessLogic\Equibles.CommonStocks.BusinessLogic.csproj" />
    <ProjectReference Include="..\Equibles.CommonStocks.Repositories\Equibles.CommonStocks.Repositories.csproj" />
    <ProjectReference Include="..\Equibles.CorporateActions.BusinessLogic\Equibles.CorporateActions.BusinessLogic.csproj" />
    <ProjectReference Include="..\Equibles.EquityMarkets.Repositories\Equibles.EquityMarkets.Repositories.csproj" />
    <ProjectReference Include="..\Equibles.CorporateActions.Repositories\Equibles.CorporateActions.Repositories.csproj" />
    <ProjectReference Include="..\Equibles.Yahoo.Repositories\Equibles.Yahoo.Repositories.csproj" />
    <ProjectReference Include="..\Equibles.Integrations.Yahoo\Equibles.Integrations.Yahoo.csproj" />
    <ProjectReference Include="..\Equibles.Sec.FinancialFacts.BusinessLogic\Equibles.Sec.FinancialFacts.BusinessLogic.csproj" />
    <ProjectReference Include="..\Equibles.Errors.BusinessLogic\Equibles.Errors.BusinessLogic.csproj" />
    <ProjectReference Include="..\Equibles.Worker\Equibles.Worker.csproj" />
  </ItemGroup>
</Project>
