<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <InternalsVisibleTo Include="Equibles.UnitTests" />
    <InternalsVisibleTo Include="Equibles.IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Equibles.Core.AutoWiring" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Equibles.CorporateActions.Repositories\Equibles.CorporateActions.Repositories.csproj" />
    <ProjectReference Include="..\Equibles.Sec.FinancialFacts.Data\Equibles.Sec.FinancialFacts.Data.csproj" />
    <ProjectReference Include="..\Equibles.Sec.FinancialFacts.Repositories\Equibles.Sec.FinancialFacts.Repositories.csproj" />
  </ItemGroup>
</Project>
