<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Equibles.Core/Equibles.Core.csproj" />
    <ProjectReference Include="../Equibles.Integrations.Common/Equibles.Integrations.Common.csproj" />
    <ProjectReference Include="../Equibles.Integrations.DelayedTrades/Equibles.Integrations.DelayedTrades.csproj" />
  </ItemGroup>
</Project>
