<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Equibles.CommonStocks.Data\Equibles.CommonStocks.Data.csproj" />
    <ProjectReference Include="..\Equibles.Core\Equibles.Core.csproj" />
    <ProjectReference Include="..\Equibles.EquityMarkets.Data\Equibles.EquityMarkets.Data.csproj" />
    <ProjectReference Include="..\Equibles.Integrations.DelayedTrades\Equibles.Integrations.DelayedTrades.csproj" />
    <ProjectReference Include="..\Equibles.Yahoo.Data\Equibles.Yahoo.Data.csproj" />
  </ItemGroup>
</Project>
